import Head from 'next/head';
import { getPosts  } from '../pages/api/alumnos';
import React, { useState, useEffect } from 'react';
import Post from '../components/alumnos';

const Home = () => {
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    getPosts()
      .then(data => setPosts(data))
  }, []);

  return (
    <>
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
    <main>
      {posts.map(post => (
        <Post key={post.id} post={post} />
      ))}
    </main>
    </>
  );
};

export default Home;